// Code generated by MockGen. DO NOT EDIT.
// Source: ../src/github.com/shashaneRanasinghe/simpleMongoAPI/internal/repository/studentRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/shashaneRanasinghe/simpleMongoAPI/internal/models"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// MockStudentRepository is a mock of StudentRepository interface.
type MockStudentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepositoryMockRecorder
}

// MockStudentRepositoryMockRecorder is the mock recorder for MockStudentRepository.
type MockStudentRepositoryMockRecorder struct {
	mock *MockStudentRepository
}

// NewMockStudentRepository creates a new mock instance.
func NewMockStudentRepository(ctrl *gomock.Controller) *MockStudentRepository {
	mock := &MockStudentRepository{ctrl: ctrl}
	mock.recorder = &MockStudentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepository) EXPECT() *MockStudentRepositoryMockRecorder {
	return m.recorder
}

// CreateStudent mocks base method.
func (m *MockStudentRepository) CreateStudent(ctx context.Context, student *models.Student) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStudent", ctx, student)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStudent indicates an expected call of CreateStudent.
func (mr *MockStudentRepositoryMockRecorder) CreateStudent(ctx, student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStudent", reflect.TypeOf((*MockStudentRepository)(nil).CreateStudent), ctx, student)
}

// DeleteStudent mocks base method.
func (m *MockStudentRepository) DeleteStudent(ctx context.Context, id primitive.ObjectID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStudent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStudent indicates an expected call of DeleteStudent.
func (mr *MockStudentRepositoryMockRecorder) DeleteStudent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStudent", reflect.TypeOf((*MockStudentRepository)(nil).DeleteStudent), ctx, id)
}

// FindAllStudents mocks base method.
func (m *MockStudentRepository) FindAllStudents(ctx context.Context) ([]models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllStudents", ctx)
	ret0, _ := ret[0].([]models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllStudents indicates an expected call of FindAllStudents.
func (mr *MockStudentRepositoryMockRecorder) FindAllStudents(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllStudents", reflect.TypeOf((*MockStudentRepository)(nil).FindAllStudents), ctx)
}

// FindStudent mocks base method.
func (m *MockStudentRepository) FindStudent(ctx context.Context, id primitive.ObjectID) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindStudent", ctx, id)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindStudent indicates an expected call of FindStudent.
func (mr *MockStudentRepositoryMockRecorder) FindStudent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindStudent", reflect.TypeOf((*MockStudentRepository)(nil).FindStudent), ctx, id)
}

// SearchStudent mocks base method.
func (m *MockStudentRepository) SearchStudent(ctx context.Context, searchString string, pagination models.Pagination, sortBy models.SortBy) (*models.StudentSearchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchStudent", ctx, searchString, pagination, sortBy)
	ret0, _ := ret[0].(*models.StudentSearchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchStudent indicates an expected call of SearchStudent.
func (mr *MockStudentRepositoryMockRecorder) SearchStudent(ctx, searchString, pagination, sortBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchStudent", reflect.TypeOf((*MockStudentRepository)(nil).SearchStudent), ctx, searchString, pagination, sortBy)
}

// UpdateStudent mocks base method.
func (m *MockStudentRepository) UpdateStudent(ctx context.Context, student *models.Student) (*models.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStudent", ctx, student)
	ret0, _ := ret[0].(*models.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStudent indicates an expected call of UpdateStudent.
func (mr *MockStudentRepositoryMockRecorder) UpdateStudent(ctx, student interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStudent", reflect.TypeOf((*MockStudentRepository)(nil).UpdateStudent), ctx, student)
}
